### ISSUE TITLE
install.sh error in macbook

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#1]
bash +x install.sh 
install.sh: line 8: syntax error near unexpected token `newline'
install.sh: line 8: `<!DOCTYPE html>'

**Comment by aronchanisme** [comment]
由于这几天用windows机器来开发，所以文件格式有点错乱，需要先dos2unix转一下格式再push，待修正

**Comment by aronchanisme** [comment]
已修复。不过还有一些mac的其他问题，例如/data/和/usr/bin/目录没权限，待解决

**Comment by dengn** [comment]
nandeng-macbookpro:mo_ctl_standalone nandeng$  wget https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh && bash +x ./install.sh
--2023-07-06 10:29:53--  https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... Read error (Operation timed out) in headers.
Retrying.

--2023-07-06 10:33:11--  (try: 2)  https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... failed: Operation timed out.
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3233 (3.2K) [text/plain]
Saving to: ‘install.sh’

install.sh                       100%[=======================================================>]   3.16K  --.-KB/s    in 0.002s  

2023-07-06 10:34:27 (1.64 MB/s) - ‘install.sh’ saved [3233/3233]

2023-07-06_10:34:27    [INFO]    Try to download mo_ctl from URL: https://ghproxy.com/https://github.com/matrixorigin/mo_ctl_standalone/archive/refs/heads/main.zip
--2023-07-06 10:34:27--  https://ghproxy.com/https://github.com/matrixorigin/mo_ctl_standalone/archive/refs/heads/main.zip
Resolving ghproxy.com (ghproxy.com)... 129.146.41.82
Connecting to ghproxy.com (ghproxy.com)|129.146.41.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘mo_ctl.zip’

mo_ctl.zip                           [ <=>                                                    ]  23.91K  --.-KB/s    in 0.1s    

2023-07-06 10:34:29 (217 KB/s) - ‘mo_ctl.zip’ saved [24480]

2023-07-06_10:34:29    [INFO]    Successfully downloaded mo_ctl
2023-07-06_10:34:29    [INFO]    Try to install mo_ctl from file mo_ctl.zip
Archive:  mo_ctl.zip
3e0428827144ef7b49fd8db9c507070fac86d11c
   creating: mo_ctl_standalone-main/
  inflating: mo_ctl_standalone-main/LICENSE  
  inflating: mo_ctl_standalone-main/README.md  
   creating: mo_ctl_standalone-main/bin/
  inflating: mo_ctl_standalone-main/bin/basic.sh  
  inflating: mo_ctl_standalone-main/bin/connect.sh  
  inflating: mo_ctl_standalone-main/bin/ddl_convert.sh  
  inflating: mo_ctl_standalone-main/bin/deploy.sh  
  inflating: mo_ctl_standalone-main/bin/get_cid.sh  
  inflating: mo_ctl_standalone-main/bin/get_conf.sh  
  inflating: mo_ctl_standalone-main/bin/help.sh  
  inflating: mo_ctl_standalone-main/bin/mysql_to_mo.sh  
  inflating: mo_ctl_standalone-main/bin/mysql_to_mo_mac.sh  
  inflating: mo_ctl_standalone-main/bin/pprof.sh  
  inflating: mo_ctl_standalone-main/bin/precheck.sh  
  inflating: mo_ctl_standalone-main/bin/restart.sh  
  inflating: mo_ctl_standalone-main/bin/set_conf.sh  
  inflating: mo_ctl_standalone-main/bin/start.sh  
  inflating: mo_ctl_standalone-main/bin/status.sh  
  inflating: mo_ctl_standalone-main/bin/stop.sh  
   creating: mo_ctl_standalone-main/conf/
  inflating: mo_ctl_standalone-main/conf/env.sh  
  inflating: mo_ctl_standalone-main/install.sh  
  inflating: mo_ctl_standalone-main/mo_ctl.sh  
mkdir: /data: Read-only file system
2023-07-06_10:34:29    [ERROR]    Failed to extract file, please check if 'unzip' is installed or file is complete

**Comment by aronchanisme** [comment]
it's fixed now, for mac user, run below command, and mo will be installed on path `/Users/$(whoami)/mo/`

For users who are running this on your Mac environment, assuming you're a non-root user, thus please run `install.sh` as
```
sudo -u $(whoami) bash +x ./install.sh
```

**Comment by dengn** [comment]
fixed.
