### ISSUE TITLE
mo_ctl 命令报错

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#10]
mo_ctl一上来就报错，观感不太好，应该让它默认等同于mo_ctl help

root@VM-16-2-debian:~# mo_ctl 
2023-07-06_19:59:25    [ERROR]    Invalid option_1 
Usage             : mo_ctl [option_1] [option_2]

[option_1]        : available: help | precheck | deploy | status | start | stop | restart | connect | get_cid | set_conf | get_conf | pprof | ddl_convert
  0) help         : print help information
  1) precheck     : check pre-requisites for mo_ctl
  2) deploy       : deploy mo onto the path configured
  3) status       : check if there's any mo process running on this machine
  4) start        : start mo-service from the path configured
  5) stop         : stop all mo-service processes found on this machine
  6) restart      : start mo-service from the path configured
  7) connect      : connect to mo via mysql client using connection info configured
  8) get_cid      : print mo commit id from the path configured
  9) pprof        : collect pprof information
  10) set_conf    : set configurations
  11) get_conf    : get configurations
  12) ddl_convert : convert ddl file to mo format from other types of database
  e.g.            : mo_ctl status

[option_2]        : Use " mo_ctl [option_1] help " to get more info
  e.g.            : mo_ctl deploy help

**Comment by aronchanisme** [comment]
fixed, now
1) `mo_ctl` works as `mo_ctl help`, and returns 0
2) `mo_ctl xxx` will throws an error and print `mo_ctl help` help info, and returns 1

**Comment by dengn** [comment]
fixed.
