### ISSUE TITLE
deploy的时候还是容易没反应

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#2]
<img width="1038" alt="image" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/4965857/fcff7be4-9682-42f8-a53b-488110f31f36">

deploy的时候还是容易没反应，可以加一个比如原始地址5s没反应就换备用地址的操作。

**Comment by dengn** [comment]
<img width="1038" alt="image" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/4965857/d6431764-599e-4509-a766-dc7ab85659f0">

**Comment by aronchanisme** [comment]
在quick start的时候有说明，看看是否足够醒目？如果需要调整的话，可以调整到deploy那步强调一下
![image](https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/65c0dc24-569e-4266-9580-d4f31f7cfb6b)
