### ISSUE TITLE
[Bug]: binary package logs folder doesn't exist

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#32]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

https://github.com/matrixorigin/matrixorigin.io.cn/issues/504

### Issue Description

https://github.com/matrixorigin/matrixorigin.io.cn/issues/504

### Steps to Reproduce

https://github.com/matrixorigin/matrixorigin.io.cn/issues/504

**Comment by aronchanisme** [comment]
https://github.com/matrixorigin/mo_ctl_standalone/issues/33#issuecomment-1631776649
