### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xuoutput** [matrixorigin/mo_ctl_standalone#37]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: e.g. v0.1.0 or 8b23a93
- OS type: Debian 11

### Issue Description

install mo_ctl timeout

### Steps to Reproduce

1. run `wget https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh && sudo -u $(whoami) bash +x ./install.sh`
```
root@VM-0-17-debian:~# wget https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh && sudo -u $(whoami) bash +x ./install.sh
--2023-07-13 17:18:56--  https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... 


failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... 
```

**Comment by aronchanisme** [comment]
It's more like a network issue, you can use backup address as stated in the doc
