### ISSUE TITLE
[Question]: MACOS 上单机部署失败

### ISSUE THREAD

**Issue by LiSong0214** [matrixorigin/mo_ctl_standalone#40]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: 
- OS type: MacOS 12.2.1
- Other info: 

### Issue Description

<img width="1112" alt="image" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/31049447/1a9b0499-5ce5-4a5a-a5e7-019b6b7f5645">

### Steps to Reproduce

https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1/#mo_ctl
按照文档顺序执行至步骤3报错

**Comment by aronchanisme** [comment]
You have failed the precheck on mysql client. Please install mysql-client first before deploying mo
https://docs.matrixorigin.cn/0.8.0/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1/#4-mysql-client
