### ISSUE TITLE
[Bug]: can not change MO_CONF_FILE to another relative path startwith "${MO_PATH}"

### ISSUE THREAD

**Issue by cyann7** [matrixorigin/mo_ctl_standalone#45]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: 09783e09a88b0a6d586eedde73d8e61a1dc14fc4
- OS type: ubuntu22.04
- 

### Issue Description

use：
mo_ctl set_conf MO_CONF_FILE="${MO_PATH}/matrixone/etc/launch-tae-CN-tae-DN/launch.toml"
I got：
2023-08-24 14:49:55.621 UTC+0800    [INFO]    Try to set conf: MO_CONF_FILE=/matrixone/etc/launch-tae-CN-tae-DN/launch.toml
2023-08-24 14:49:55.636 UTC+0800    [INFO]    Setting conf MO_CONF_FILE=/matrixone/etc/launch-tae-CN-tae-DN/launch.toml

${MO_PATH} is not in the path
![image](https://github.com/matrixorigin/mo_ctl_standalone/assets/47444607/d86f128b-f92e-4151-b0d0-a9eac1d049a0)

what I hope:
 set conf MO_CONF_FILE="${MO_PATH}/matrixone/etc/launch-tae-CN-tae-DN/launch.toml"

### Steps to Reproduce

mo_ctl set_conf MO_CONF_FILE="${MO_PATH}/matrixone/etc/launch-tae-CN-tae-DN/launch.toml"

**Comment by aronchanisme** [comment]
Please add a `\` before `$`, like this:
```bash
mo_ctl set_conf MO_CONF_FILE="\${MO_PATH}/matrixone/etc/launch-tae-CN-tae-DN/launch.toml"
```

@lacrimosaprinz  hi could you please help update the docs as well? I will add more info in the 'set_conf' part.
