### ISSUE TITLE
[Bug]: install mo_ctl failed because can not touch: /usr/local/bin/mo_ctl

### ISSUE THREAD

**Issue by cyann7** [matrixorigin/mo_ctl_standalone#48]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: 
- OS type: e.g. MacOS 14
- Other info:

### Issue Description

macOS新机器上，安装 mo_ctl失败，检查发现是无法 touch: /usr/local/bin/mo_ctl，发现是/usr/local下不存在文件夹bin/，后面自己创建一个bin/，重新安装就ok了
<img width="731" alt="截屏2023-10-27 11 39 32" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/47444607/1cf9078f-c2e9-47f6-bcb8-b15a198a6522">

### Steps to Reproduce

wget https://raw.githubusercontent.com/matrixorigin/mo_ctl_standalone/main/install.sh && sudo -u $(whoami) bash +x ./install.sh

**Comment by aronchanisme** [comment]
fixed

**Comment by cyann7** [comment]
Retest successful
