### ISSUE TITLE
ddl convert没有完全成功

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#7]
<img width="560" alt="image" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/4965857/8f159b49-e707-4407-b418-c1743f08a0fa">

<img width="678" alt="image" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/4965857/498221af-6c8e-410b-b89f-ec452cebbfcd">

**Comment by aronchanisme** [comment]
fixed
